config/routes.rb
Rails.application.routes.draw do
  
  resources :nuevos
  
  resources :zombies do
      resources :brains
  end      
  get "sexto_repo/cerebros", to: 'brains#index', as: 'brains'    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brain.rb
class Brain < ApplicationRecord
	belongs_to :zombie
    validates :flavor,presence:true
    validates :iq, numericality:{only_integer:true, message: "Solo numeros enteros"}
end

app/models/nuevo.rb
class Nuevo < ApplicationRecord
end

app/models/zombie.rb
class Zombie < ApplicationRecord
   
    has_many :brains, dependent: :destroy
    validates :name, presence: true
    validates :bio, length: { maximum: 100 }
    validates :age, numericality:{only_integer:true, message: "Solo numeros enteros"}
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
    @zombie=Zombie.find(params[:zombie_id]);  
    @brain = @zombie.brains.create(brain_params);
      
    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'Brain was successfully created.' }
        format.json { render :show, status: :created, location: @brain }
          format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'Brain was successfully updated.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'Brain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
      params.require(:brain).permit(:flavor,:iq,:fresh,:zombie_id)
    end
end

app/controllers/nuevos_controller.rb
class NuevosController < ApplicationController
  before_action :set_nuevo, only: [:show, :edit, :update, :destroy]

  # GET /nuevos
  # GET /nuevos.json
  def index
    @nuevos = Nuevo.all
  end

  # GET /nuevos/1
  # GET /nuevos/1.json
  def show
  end

  # GET /nuevos/new
  def new
    @nuevo = Nuevo.new
  end

  # GET /nuevos/1/edit
  def edit
  end

  # POST /nuevos
  # POST /nuevos.json
  def create
    @nuevo = Nuevo.new(nuevo_params)

    respond_to do |format|
      if @nuevo.save
        format.html { redirect_to @nuevo, notice: 'Nuevo was successfully created.' }
        format.json { render :show, status: :created, location: @nuevo }
      else
        format.html { render :new }
        format.json { render json: @nuevo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nuevos/1
  # PATCH/PUT /nuevos/1.json
  def update
    respond_to do |format|
      if @nuevo.update(nuevo_params)
        format.html { redirect_to @nuevo, notice: 'Nuevo was successfully updated.' }
        format.json { render :show, status: :ok, location: @nuevo }
      else
        format.html { render :edit }
        format.json { render json: @nuevo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nuevos/1
  # DELETE /nuevos/1.json
  def destroy
    @nuevo.destroy
    respond_to do |format|
      format.html { redirect_to nuevos_url, notice: 'Nuevo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nuevo
      @nuevo = Nuevo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nuevo_params
      params.require(:nuevo).permit(:fuerza)
    end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
    @rotten_zombies=Zombie.where(rotten:true)
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age,:email,:rotten,:avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/helpers/nuevos_helper.rb
module NuevosHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/brains/_brain.html.erb
<%= div_for brain do%>

 <ul class="list-group">
  <li class="list-group-item justify-content-between">
    <%=  time_ago_in_words(brain.created_at)%>
    <span class="badge badge-default badge-pill"><%=brain.flavor%></span>
  </li>
</ul>


<%end%>    

app/views/brains/_form.html.erb
<%= form_for(brain) do |f| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= f.collection_select :zombie_id,Zombie.order(:name),:id,:name, include_blank:true%>
  </div>

  <div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>
  <div class="field">
    <%= f.label :iq %>
    <%= f.number_field :iq %>
  </div> 
  <div class="field">
    <%= f.label :fresh %>
    <%= f.check_box :fresh %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= form_for(brain) do |f| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= f.collection_select :zombie_id,Zombie.order(:name),:id,:name, include_blank:true%>
  </div>

  <div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>
  <div class="field">
    <%= f.label :iq %>
    <%= f.number_field :iq %>
  </div> 
  <div class="field">
    <%= f.label :fresh %>
    <%= f.check_box :fresh %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brains/create.js.erb
var new_brain=$("<%= escape_javascript(render(:partial=>@brain))%>").hide();
$('#brains').prepend(new_brain);
$('#brain_<%= @brain.id%>').fadeIn('slow');
$('#new_brain')[0].reset();

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Show', @brain %> |
<%= link_to 'Back', brains_path %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
      
      <th>iq</th>
      
      
      <th>fresh</th>
      
    </tr>
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.flavor %></td>
        <td><%= brain.iq %></td>
        <td><% if brain.fresh %>
            <%= image_tag 'brains/1496336964_Brain-Games-grey.png', class: 'brains_fresh'%>
        <%else %>    
            <%= image_tag 'brains/1496336978_Brain-Games-red', class: 'brains_fresh'%>
        <%end%>    
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @brain.flavor %>
  <strong>iq:</strong>
  <%= @brain.iq %>
  <strong>fresh:</strong>
  <%= @brain.fresh %>
</p>

<%= link_to 'Edit', edit_brain_path(@brain) %> |
<%= link_to 'Back', brains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sextoa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Aplicacion Zombiess</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown"  aria-expanded="true">
          Zombie
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" ><%= link_to 'Lista Zombie', zombies_path %></a>
          <a class="dropdown-item" href="#"><%= link_to 'Nuevo Zombie', new_zombie_path %></a>
        </div>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
      
  </body>
</html>

app/views/nuevos/_form.html.erb
<%= form_for(nuevo) do |f| %>
  <% if nuevo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nuevo.errors.count, "error") %> prohibited this nuevo from being saved:</h2>

      <ul>
      <% nuevo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fuerza %>
    <%= f.number_field :fuerza %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nuevos/edit.html.erb
<h1>Editing Nuevo</h1>

<%= render 'form', nuevo: @nuevo %>

<%= link_to 'Show', @nuevo %> |
<%= link_to 'Back', nuevos_path %>

app/views/nuevos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nuevos</h1>

<table>
  <thead>
    <tr>
      <th>Fuerza</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nuevos.each do |nuevo| %>
      <tr>
        <td><%= nuevo.fuerza %></td>
        <td><%= link_to 'Show', nuevo %></td>
        <td><%= link_to 'Edit', edit_nuevo_path(nuevo) %></td>
        <td><%= link_to 'Destroy', nuevo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nuevo', new_nuevo_path %>

app/views/nuevos/new.html.erb
<h1>New Nuevo</h1>

<%= render 'form', nuevo: @nuevo %>

<%= link_to 'Back', nuevos_path %>

app/views/nuevos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fuerza:</strong>
  <%= @nuevo.fuerza %>
</p>

<%= link_to 'Edit', edit_nuevo_path(@nuevo) %> |
<%= link_to 'Back', nuevos_path %>

app/views/zombies/_form.html.erb
<%= form_for(zombie) do |f| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
<div class="row">
<form >
 <div class="col-xl-6">
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name ,class:"form-control"%>
  </div>
  <div class="field form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio ,class:"form-control"%>
  </div> 
  <div class="field form-group">
    <%= f.label :age %>
    <%= f.number_field :age ,class:"form-control"%>
  </div>
 </div>
 
 <div class="col-xl-6">
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.text_field :email,class:"form-control" %> 
  </div>    
  <div class="field form-group">
    <%= f.label :rotten %>
    <%= f.text_field :rotten,class:"form-control" %> 
  </div>
   <div class="field form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar,class:"form-control" %> 
  </div>
    </div>  
</form>
</div>   
  <div class="actions">
    <%= f.submit class:"btn btn-success", type:"submit" %>
  </div>

</div>  
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>
<br>
<%= link_to 'Show', @zombie, class:"btn btn-info" %> |
<%= link_to 'Back', zombies_path, class:"btn btn-info" %>

app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombies</h1>
<div class="container">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>Email</th>
      <th>Rotten</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rotten_zombies.each do |zombie| %>
      <tr>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
        <td><%= zombie.email %></td>
        <td><%= zombie.rotten ? "yes" : "No" %></td>
        <td><%=image_tag zombie.avatar, class:"avatar_index" %></td>
        <td ><%= link_to 'Show', zombie, class: "btn btn-primary" %></td>
        <td ><%= link_to 'Edit', edit_zombie_path(zombie),class:"btn btn-primary" %></td>
        <td ><%= link_to 'Destroy', zombie,class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path,class:"btn btn-info" %>
</div>

app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path,class:"btn btn-info" %>

app/views/zombies/show.html.erb
<div class="show">
<div class="container"> 
<div class="row">
    <div class="col-lg-6">
        <%=image_tag @zombie.avatar, class:"avatar"%>
    </div>
<div class="col-lg-6">
<table class="table table-reflow">
  <thead>
    <tr>
      
      <th>Age</th>
      <th>Email</th>
      <th>Rotten</th>
    </tr>
  </thead>
  <tbody>
    <tr> 
      <td><%= @zombie.age %></td>
      <td><%=@zombie.email%></td>
      <td><%=@zombie.rotten%></td>
    </tr>
</table> 
</div> 
 </div>
<div id="brains">
    <%= render :partial=>@zombie.brains.reverse%>
</div>

<%= form_for([@zombie, Brain.new],remote:true)do|f|%>
  <form class="formulario">
    <div class="field form-group">
        <%= f.label :flavor%>
        <%= f.text_field :flavor,class:"form-control"%>
    </div>
    <div class="field form-group">
        <%= f.label :iq%>
        <%= f.number_field :iq,class:"form-control"%>
    </div>
    <div class="field form-group">
        <%= f.label :fresh%>
        <%= f.check_box :fresh,class:"form-control"%>
    </div>
    <div class="action">
        <%= f.submit "Add brain",class:"btn btn-primary"%>
    </div>
    </form>
</div>
</div>       
    <%end%>
<br>    
<%= link_to 'Edit', edit_zombie_path(@zombie),class:"btn btn-info" %> |
<%= link_to 'Back', zombies_path,class:"btn btn-info" %>